apiVersion: istio.openshift.com/v1alpha3
kind: ControlPlane
metadata:
  name: default-controlplane
spec:
  global:
    proxy:
      autoInject: disabled
      privileged: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 128Mi
    multiCluster:
      enabled: false

  security:
    enabled: true
    cleanUpOldCA: false

  ingress:
    autoscaleMin: 0
    autoscaleMax: 0

  gateways:
    istio-egressgateway:
      enabled: true
      autoscaleMin: 0
      autoscaleMax: 0
    istio-ingressgateway:
      autoscaleMin: 0
      autoscaleMax: 0

  mixer:
    autoscaleMin: 0
    autoscaleMax: 0

    policy:
      enabled: true
      autoscaleEnabled: false

    telemetry:
      enabled: true
      autoscaleEnabled: false
      resources:
        requests:
          cpu: 100m
          memory: 1G
        limits:
          cpu: 500m
          memory: 4G

  pilot:
    autoscaleMin: 0
    autoscaleMax: 0
    traceSampling: 100.0

  sidecarInjectorWebhook:
    enabled: true
    enableNamespacesByDefault: true

  grafana:
    enabled: true

  tracing:
    enabled: true

  kiali:
    enabled: true
    hub: kiali
    tag: v0.15.0
