apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: istiocontrolplanes.istio.openshift.com
spec:
  group: istio.openshift.com
  names:
    kind: IstioControlPlane
    listKind: IstioControlPlaneList
    plural: istiocontrolplanes
    singular: istiocontrolplane
  scope: Namespaced
  version: v1alpha3
