apiVersion: istio.openshift.com/v1alpha3
kind: ControlPlane
metadata:
  name: default-controlplane
spec:
  launcher:
    enabled: true
  threeScale:
    enabled: true
  istio:
    global:
      proxy:
        autoInject: disabled
        privileged: false
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi
      multiCluster:
        enabled: false

    security:
      enabled: true
      cleanUpOldCA: false

    gateways:
      istio-egressgateway:
        enabled: true
        autoscaleEnabled: false
      istio-ingressgateway:
        enabled: true
        autoscaleEnabled: false

    mixer:
      policy:
        enabled: true
        autoscaleEnabled: false

      telemetry:
        enabled: true
        autoscaleEnabled: false
        resources:
          requests:
            cpu: 100m
            memory: 1G
          limits:
            cpu: 500m
            memory: 4G

    pilot:
      autoscaleEnabled: false
      traceSampling: 100.0

    sidecarInjectorWebhook:
      enabled: true
      enableNamespacesByDefault: true

    prometheus:
      enabled: true
      ingress:
        enabled: true

    grafana:
      enabled: true
      ingress:
        enabled: true

    tracing:
      enabled: true
      ingress:
        enabled: true

    kiali:
      enabled: true
      hub: kiali
      tag: v0.15.0
      ingress:
        enabled: true
      dashboard:
        user: admin
        passphrase: admin
