apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: installations.istio.openshift.com
spec:
  group: istio.openshift.com
  names:
    kind: Installation
    plural: installations
    singular: installation
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
