apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: servicemeshmembers.maistra.io
spec:
  group: maistra.io
  names:
    kind: ServiceMeshMember
    listKind: ServiceMeshMemberList
    plural: servicemeshmembers
    singular: servicemeshmember
    shortNames:
      - smm
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  additionalPrinterColumns:
  - JSONPath: .spec.controlPlaneRef.namespace
    description: The ServiceMeshControlPlane's namespace that this namespace belongs to
    name: "Control Plane Namespace"
    type: string
  - JSONPath: .spec.controlPlaneRef.name
    description: The ServiceMeshControlPlane that this namespace belongs to
    name: "Control Plane"
    type: string
