kind: ConfigMap
apiVersion: v1
metadata:
  name: launcher
  namespace: {{ .Release.Namespace }}
  labels:
    app: fabric8-launcher
    chart: {{ template "launcher.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  launcher.missioncontrol.github.username: {{ .Values.LAUNCHER_MISSIONCONTROL_GITHUB_USERNAME }}
  launcher.missioncontrol.github.token: {{ .Values.LAUNCHER_MISSIONCONTROL_GITHUB_TOKEN }}
  launcher.missioncontrol.openshift.api.url: {{ .Values.LAUNCHER_MISSIONCONTROL_OPENSHIFT_API_URL }}
  launcher.missioncontrol.openshift.console.url: {{ .Values.LAUNCHER_MISSIONCONTROL_OPENSHIFT_CONSOLE_URL }}
  launcher.backend.catalog.filter: {{ .Values.LAUNCHER_BACKEND_CATALOG_FILTER }}
  launcher.backend.catalog.git.repository: {{ .Values.LAUNCHER_BOOSTER_CATALOG_REPOSITORY }}
  launcher.backend.catalog.git.ref: {{ .Values.LAUNCHER_BOOSTER_CATALOG_REF }}
  launcher.backend.catalog.reindex.token: {{ .Values.LAUNCHER_BACKEND_CATALOG_REINDEX_TOKEN }}
  launcher.backend.documentation.reload.token: {{ .Values.LAUNCHER_BACKEND_CATALOG_REINDEX_TOKEN }}
  launcher.backend.environment: {{ .Values.LAUNCHER_BACKEND_ENVIRONMENT }}
  launcher.keycloak.url: {{ .Values.LAUNCHER_KEYCLOAK_URL }}
  launcher.keycloak.realm: {{ .Values.LAUNCHER_KEYCLOAK_REALM }}
  launcher.tracker.segment.token: {{ .Values.LAUNCHER_TRACKER_SEGMENT_TOKEN }}
  launcher.backend.url: /launch/api
  launcher.missioncontrol.url: /launch
  osio.keycloak.saas.url: https://api.prod-preview.openshift.io
  osio.openshift.api.url: https://f8osoproxy-test-dsaas-preview.b6ff.rh-idev.openshiftapps.com
  osio.wit.url: https://api.prod-preview.openshift.io
  osio.auth.url: https://auth.prod-preview.openshift.io
  osio.jenkins.url: https://jenkins.prod-preview.openshift.io
  osio.sentry.dsn: ""

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: launcher-clusters
  namespace: {{ .Release.Namespace }}
  labels:
    app: fabric8-launcher
    chart: {{ template "launcher.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  openshift-clusters.yaml: |-
    - id: starter-us-east-1
      apiUrl: https://api.starter-us-east-1.openshift.com
      consoleUrl: https://console.starter-us-east-1.openshift.com
      type: starter
    - id: starter-us-west-1
      apiUrl: https://api.starter-us-west-1.openshift.com
      consoleUrl: https://console.starter-us-west-1.openshift.com
      type: starter
    - id: starter-us-west-2
      apiUrl: https://api.starter-us-west-2.openshift.com
      consoleUrl: https://console.starter-us-west-2.openshift.com
      type: starter
    - id: starter-ca-central-1
      apiUrl: https://api.starter-ca-central-1.openshift.com
      consoleUrl: https://console.starter-ca-central-1.openshift.com
      type: starter
    - id: pro-us-east-1
      apiUrl: https://api.pro-us-east-1.openshift.com
      consoleUrl: https://console.pro-us-east-1.openshift.com
      type: pro
    - id: pro-eu-west-1
      apiUrl: https://api.pro-eu-west-1.openshift.com
      consoleUrl: https://console.pro-eu-west-1.openshift.com
      type: pro
    - id: pro-ap-southeast-2
      apiUrl: https://api.pro-ap-southeast-2.openshift.com
      consoleUrl: https://console.pro-ap-southeast-2.openshift.com
      type: pro
