apiVersion: project.openshift.io/v1
kind: ProjectRequest
metadata:
  name: {{ .Release.Namespace }}
  labels:
    app: fabric8-launcher
    chart: {{ template "launcher.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    "istio.openshift.com/ignore-namespace": ignore
  description: "This project contains resources for ...."
