apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: fabric8-launcher
    chart: {{ template "launcher.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    service: launcher-frontend
  name: fabric8-launcher-view
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get", "list", "watch"]
