apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: fabric8-launcher
    chart: {{ template "launcher.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    service: configmapcontroller
  name: configmapcontroller-edit
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: configmapcontroller
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: fabric8-launcher
    chart: {{ template "launcher.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    service: launcher-frontend
  name: fabric8-launcher-view
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: fabric8-launcher-view
subjects:
- kind: Group
  name: system:authenticated
