apiVersion: v1
kind: RoleBinding
metadata:
  labels:
    app: fabric8-launcher
    chart: {{ template "launcher.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    service: configmapcontroller
  name: configmapcontroller-edit
  namespace: {{ .Release.Namespace }}
roleRef:
  name: edit
subjects:
- kind: ServiceAccount
  name: configmapcontroller
  namespace: {{ .Release.Namespace }}
