apiVersion: v1
kind: Secret
metadata:
  name: launcher-backend-token
  namespace: {{ .Release.Namespace }}
  labels:
    app: fabric8-launcher
    chart: {{ template "launcher.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    service: launcher-backend
  annotations:
    "kubernetes.io/service-account.name": launcher-backend
type: "kubernetes.io/service-account-token"
