kind: Service
apiVersion: v1
metadata:
  labels:
    app: fabric8-launcher
    chart: {{ template "launcher.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    service: launcher-backend
  name: launcher-backend
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: launcher-backend
  sessionAffinity: None
  type: ClusterIP

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: fabric8-launcher
    chart: {{ template "launcher.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    service: launcher-frontend
  name: launcher-frontend
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: launcher-frontend
  sessionAffinity: None
  type: ClusterIP
