apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: fabric8-launcher
    chart: {{ template "launcher.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    service: configmapcontroller
  name: configmapcontroller
  namespace: {{ .Release.Namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: fabric8-launcher
    chart: {{ template "launcher.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    service: launcher-backend
  name: launcher-backend
  namespace: {{ .Release.Namespace }}
