{{- if .Values.ingress.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kiali
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kiali.name" . }}
    chart: {{ template "kiali.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  to:
    kind: Service
    name: kiali
  port:
    targetPort: 20001
  tls:
    termination: reencrypt
{{- end -}}
