{{ .Values.dashboard.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dashboard.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kiali.name" . }}
    chart: {{ template "kiali.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
{{ if .Values.dashboard.user }}
  {{ .Values.dashboard.usernameKey }}: {{ b64enc .Values.dashboard.user }}
{{ end }}
{{ if .Values.dashboard.passphrase }}
  {{ .Values.dashboard.passphraseKey }}:  {{ b64enc .Values.dashboard.passphrase }}
{{ end }}
{{ end }}
