{{- if .Values.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
    chart: {{ template "prometheus.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  to:
    kind: Service
    name: prometheus
{{- end }}
